
/**************************************************************
 *	
 *	BirdSFX, 8 bit, 11025Hz,
 *	1 channel, 5227 bytes/channel
 *	Total Size: 1 * 5227 + 4 (header) = 5271 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Sarah\Documents\School\2017 Spring\CS 2261\M5_SarahVeith\BirdSFX.aiff
 *	Time-stamp: Wed Apr 19 16:52:29 2017
 *	
 **************************************************************/

#ifndef __BIRDSFXH__
#define __BIRDSFXH__

#define BIRDSFXFREQ 11025
#define BIRDSFXLEN 5227

extern const unsigned char BirdSFX[5227];

#endif /* __BIRDSFXH__ */
