
/**************************************************************
 *	
 *	CatMeowSFX, 8 bit, 11025Hz,
 *	1 channel, 15109 bytes/channel
 *	Total Size: 1 * 15109 + 4 (header) = 15153 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Sarah\Documents\School\2017 Spring\CS 2261\M5_SarahVeith\CatMeowSFX.aiff
 *	Time-stamp: Wed Apr 19 19:00:40 2017
 *	
 **************************************************************/

#ifndef __CATMEOWSFXH__
#define __CATMEOWSFXH__

#define CATMEOWSFXFREQ 11025
#define CATMEOWSFXLEN 15109

extern const unsigned char CatMeowSFX[15109];

#endif /* __CATMEOWSFXH__ */
