
/**************************************************************
 *	
 *	CursorSFX, 8 bit, 11025Hz,
 *	1 channel, 692 bytes/channel
 *	Total Size: 1 * 692 + 4 (header) = 736 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Sarah\Documents\School\2017 Spring\CS 2261\M5_SarahVeith\CursorSFX.aiff
 *	Time-stamp: Wed Apr 19 16:52:18 2017
 *	
 **************************************************************/

#ifndef __CURSORSFXH__
#define __CURSORSFXH__

#define CURSORSFXFREQ 11025
#define CURSORSFXLEN 692

extern const unsigned char CursorSFX[692];

#endif /* __CURSORSFXH__ */
