
/**************************************************************
 *	
 *	GameSong, 8 bit, 11025Hz,
 *	1 channel, 377651 bytes/channel
 *	Total Size: 1 * 377651 + 4 (header) = 377695 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Sarah\Documents\School\2017 Spring\CS 2261\M5_SarahVeith\GameSong.aiff
 *	Time-stamp: Wed Apr 19 17:14:14 2017
 *	
 **************************************************************/

#ifndef __GAMESONGH__
#define __GAMESONGH__

#define GAMESONGFREQ 11025
#define GAMESONGLEN 377651

extern const unsigned char GameSong[377651];

#endif /* __GAMESONGH__ */
