
/**************************************************************
 *	
 *	MysterySong, 8 bit, 11025Hz,
 *	1 channel, 602208 bytes/channel
 *	Total Size: 1 * 602208 + 4 (header) = 602252 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Sarah\Documents\School\2017 Spring\CS 2261\M3_SarahVeith\MysterySong.aiff
 *	Time-stamp: Tue Apr 04 20:21:30 2017
 *	
 **************************************************************/

#ifndef __MYSTERYSONGH__
#define __MYSTERYSONGH__

#define MYSTERYSONGFREQ 11025
#define MYSTERYSONGLEN 602208

extern const unsigned char MysterySong[602208];

#endif /* __MYSTERYSONGH__ */
