
/**************************************************************
 *	
 *	ParkSong, 8 bit, 11025Hz,
 *	1 channel, 688320 bytes/channel
 *	Total Size: 1 * 688320 + 4 (header) = 688364 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Sarah\Documents\School\2017 Spring\CS 2261\M5_SarahVeith\ParkSong.aiff
 *	Time-stamp: Wed Apr 19 16:52:45 2017
 *	
 **************************************************************/

#ifndef __PARKSONGH__
#define __PARKSONGH__

#define PARKSONGFREQ 11025
#define PARKSONGLEN 688320

extern const unsigned char ParkSong[688320];

#endif /* __PARKSONGH__ */
